import { Pipe, PipeTransform } from '@angular/core';


/** This is a custom pipe, generated by the command: ng generate pipe 
 * Everything but the impementation of the 'transform' method is pre-generated.
*/

@Pipe({
  name: 'convertDistance'
})
export class ConvertDistancePipe implements PipeTransform {

  transform(value: any, targetUnits: string): any {
    let numericValue = parseFloat(value);
    if (Number.isNaN(numericValue)) {
      return 0;
    } else {
      numericValue = numericValue * 1.609;
    }
    switch (targetUnits) {
      case 'km':
        return numericValue;
      case 'm':
        return numericValue * 1000;
      case 'cm':
        return numericValue * 100000;
      default:
        return '';
    }
  }

}
